namespace Runtime.DataFramework.Properties
{
	public enum PropertyName
	{
		rarity,
		danger,
		taste,
		vigiliance,
		attack_range,
		bait_adjectives,
		max_stack,
		stack_size,
		custom_properties,
		custom_property,
		custom_property_data,
		health,
		tags,
		resource,
		resource_list,
		test_resource_dict,
		test_silver_resource,
		test_gold_resource,
		test,
		test_interest,
		test_interest_list,
		test_interest_dict,
		//weapon properties
		base_damage,
		attack_speed,
		range,
		ammo_size,
		reload_speed,
		bullets_per_shot,
		spread,
		recoil,
		charge_speed,
		bullet_speed,
		test_hashset
	}
}
