name: Docs

on:
  push:
    branches:
    - develop
    - doc-fx
    paths:
    - src/**
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: DocFX Build
      run: docfx docfx_project/docfx.json
      continue-on-error: false

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
