name: Docs

on:
  push:
    branches:
    - develop
    - doc-fx

       #if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    
 
jobs:
 buildDoc:
    name: Build Doc
    runs-on: windows-2019
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2021.3.25f1
        targetPlatform:
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Setup Unity Version
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Install DocFX
        run: |
          mkdir ~/docfx_install
          cd ~/docfx_install
          dotnet tool install --global docfx
      - name: Debug information
        run: |
          dotnet --info
          ls
          ls Assets/
          
      - name: Build docs
        run: |
          docfx docfx_project/docfx.json
          ls
        continue-on-error: true

    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docfx_project/_site
        


  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #         ref: doc-fx
         

  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: '6.x' 

  #   - name: Install DocFX
  #     run: |
  #       mkdir ~/docfx_install
  #       cd ~/docfx_install
  #       dotnet tool install --global docfx
  #   - name: Debug information
  #     run: |
  #       dotnet --info
  #       ls
  #       ls Assets/
  #   - name: Build docs
  #     run: |
  #       docfx docfx_project/docfx.json
  #       ls
  #     continue-on-error: true

    
  #   - name: Deploy to GitHub Pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: docfx_project/_site
        
