name: Docs

on:
  push:
    branches:
    - develop
    - doc-fx

       #if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    

jobs:
 buildDoc:
    name: Build Doc
    runs-on: windows-2019
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Setup Unity Version
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: '2021.3.25f1'

      - name: Load Unity Project
        run: unity-editor -batchmode -projectPath $GITHUB_WORKSPACE -quit

      - name: Install DocFX
        run: |
          mkdir ~/docfx_install
          cd ~/docfx_install
          dotnet tool install --global docfx
      - name: Debug information
        run: |
          dotnet --info
          ls
          ls Assets/
          
      - name: Build docs
        run: |
          docfx docfx_project/docfx.json
          ls
        continue-on-error: true

    
  #   - name: Deploy to GitHub Pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: docfx_project/_site
        


  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #         ref: doc-fx
         

  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: '6.x' 

  #   - name: Install DocFX
  #     run: |
  #       mkdir ~/docfx_install
  #       cd ~/docfx_install
  #       dotnet tool install --global docfx
  #   - name: Debug information
  #     run: |
  #       dotnet --info
  #       ls
  #       ls Assets/
  #   - name: Build docs
  #     run: |
  #       docfx docfx_project/docfx.json
  #       ls
  #     continue-on-error: true

    
  #   - name: Deploy to GitHub Pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: docfx_project/_site
        
