name: Docs

on:
  push:
    branches:
    - develop
    - doc-fx

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: doc-fx
         

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x' 

    - name: Install DocFX
      run: dotnet tool install --global docfx

    - name: Debug information
      run: |
        dotnet --info
        cat docfx_project/

    - name: Build docs
      run: docfx docfx_project/docfx.json
      continue-on-error: true

    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
